<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Introduction to biocthis • biocthis</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha256-bZLfwXAP04zRMK2BjiO8iu9pf4FbLqX6zitd+tIvLhE=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Introduction to biocthis">
<meta property="og:description" content="biocthis">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    

    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">biocthis</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">1.3.7</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../articles/biocthis.html">Get started</a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/biocthis_dev_notes.html">biocthis developer notes</a>
    </li>
  </ul>
</li>
<li>
  <a href="../news/index.html">Changelog</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/lcolladotor/biocthis/" class="external-link">
    <span class="fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="biocthis_files/header-attrs-2.10/header-attrs.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Introduction to biocthis</h1>
                        <h4 data-toc-skip class="author">Leonardo Collado-Torres</h4>
            <address class="author_afil">
      Lieber Institute for Brain Development, Johns Hopkins Medical CampusCenter for Computational Biology, Johns Hopkins University<br><a class="author_email" href="mailto:#"></a><a href="mailto:lcolladotor@gmail.com" class="email">lcolladotor@gmail.com</a>
      </address>
                  
            <h4 data-toc-skip class="date">9 August 2021</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/lcolladotor/biocthis/blob/master/vignettes/biocthis.Rmd" class="external-link"><code>vignettes/biocthis.Rmd</code></a></small>
      <div class="hidden name"><code>biocthis.Rmd</code></div>

    </div>

    
    
<p>Note that <em><a href="https://bioconductor.org/packages/3.14/biocthis" class="external-link">biocthis</a></em> is not a Bioconductor-core package and as such it is not a Bioconductor official package. It was made by and for Leonardo Collado-Torres so he could more easily maintain and create Bioconductor packages as listed at <a href="https://lcolladotor.github.io/pkgs/" class="external-link">lcolladotor.github.io/pkgs/</a>. Hopefully <em><a href="https://bioconductor.org/packages/3.14/biocthis" class="external-link">biocthis</a></em> will be helpful for you too.</p>
<div id="basics" class="section level1">
<h1 class="hasAnchor">
<a href="#basics" class="anchor" aria-hidden="true"></a>Basics</h1>
<div id="install-biocthis" class="section level2">
<h2 class="hasAnchor">
<a href="#install-biocthis" class="anchor" aria-hidden="true"></a>Install <code>biocthis</code>
</h2>
<p><code>R</code> is an open-source statistical environment which can be easily modified to enhance its functionality via packages. <em><a href="https://bioconductor.org/packages/3.14/biocthis" class="external-link">biocthis</a></em> is a <code>R</code> package available via the <a href="http://bioconductor.org" class="external-link">Bioconductor</a> repository for packages. <code>R</code> can be installed on any operating system from <a href="https://cran.r-project.org/" class="external-link">CRAN</a> after which you can install <em><a href="https://bioconductor.org/packages/3.14/biocthis" class="external-link">biocthis</a></em> by using the following commands in your <code>R</code> session:</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw">if</span> <span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/ns-load.html" class="external-link">requireNamespace</a></span><span class="op">(</span><span class="st">"BiocManager"</span>, quietly <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span>
    <span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html" class="external-link">install.packages</a></span><span class="op">(</span><span class="st">"BiocManager"</span><span class="op">)</span>
<span class="op">}</span>

<span class="fu">BiocManager</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/BiocManager/man/install.html" class="external-link">install</a></span><span class="op">(</span><span class="st">"biocthis"</span><span class="op">)</span>

<span class="co">## Check that you have a valid Bioconductor installation</span>
<span class="fu">BiocManager</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/BiocManager/man/valid.html" class="external-link">valid</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<p>You can install the development version from <a href="https://github.com/" class="external-link">GitHub</a> with:</p>
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">BiocManager</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/BiocManager/man/install.html" class="external-link">install</a></span><span class="op">(</span><span class="st">"lcolladotor/biocthis"</span><span class="op">)</span></code></pre></div>
</div>
<div id="required-knowledge" class="section level2">
<h2 class="hasAnchor">
<a href="#required-knowledge" class="anchor" aria-hidden="true"></a>Required knowledge</h2>
<p><em><a href="https://bioconductor.org/packages/3.14/biocthis" class="external-link">biocthis</a></em> is based on many other packages and in particular in those that have implemented the infrastructure needed for creating tidyverse-style R packages. That is <em><a href="https://CRAN.R-project.org/package=usethis" class="external-link">usethis</a></em> (Wickham and Bryan, 2021), <em><a href="https://CRAN.R-project.org/package=devtools" class="external-link">devtools</a></em> (Wickham, Hester, and Chang, 2021), and <em><a href="https://CRAN.R-project.org/package=testthat" class="external-link">testthat</a></em> (Wickham, 2011). It will also be helpful if you are familiar with <em><a href="https://CRAN.R-project.org/package=styler" class="external-link">styler</a></em> (Müller and Walthert, 2021). Finally, we highly recommend that you run <em><a href="https://bioconductor.org/packages/3.14/biocthis" class="external-link">biocthis</a></em> within <a href="https://www.rstudio.com/products/rstudio/download" class="external-link">RStudio Desktop</a>.</p>
<p>If you are asking yourself the question “Where do I start using Bioconductor?” you might be interested in <a href="http://lcolladotor.github.io/2014/10/16/startbioc/#.VkOKbq6rRuU" class="external-link">this blog post</a>.</p>
</div>
<div id="asking-for-help" class="section level2">
<h2 class="hasAnchor">
<a href="#asking-for-help" class="anchor" aria-hidden="true"></a>Asking for help</h2>
<p>As package developers, we try to explain clearly how to use our packages and in which order to use the functions. But <code>R</code> and <code>Bioconductor</code> have a steep learning curve so it is critical to learn where to ask for help. The blog post quoted above mentions some but we would like to highlight the <a href="https://support.bioconductor.org/" class="external-link">Bioconductor support site</a> as the main resource for getting help: remember to use the <code>biocthis</code> tag and check <a href="https://support.bioconductor.org/t/biocthis/" class="external-link">the older posts</a>. Other alternatives are available such as creating GitHub issues and tweeting. However, please note that if you want to receive help you should adhere to the <a href="http://www.bioconductor.org/help/support/posting-guide/" class="external-link">posting guidelines</a>. It is particularly critical that you provide a small reproducible example and your session information so package developers can track down the source of the error.</p>
</div>
<div id="citing-biocthis" class="section level2">
<h2 class="hasAnchor">
<a href="#citing-biocthis" class="anchor" aria-hidden="true"></a>Citing <code>biocthis</code>
</h2>
<p>We hope that <em><a href="https://bioconductor.org/packages/3.14/biocthis" class="external-link">biocthis</a></em> will be useful for your work. Please use the following information to cite the package and the overall approach. Thank you!</p>
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">## Citation info</span>
<span class="fu"><a href="https://rdrr.io/r/utils/citation.html" class="external-link">citation</a></span><span class="op">(</span><span class="st">"biocthis"</span><span class="op">)</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; Collado-Torres L (2021). _Automate package and project setup for</span>
<span class="co">#&gt; Bioconductor packages_. doi: 10.18129/B9.bioc.biocthis (URL:</span>
<span class="co">#&gt; https://doi.org/10.18129/B9.bioc.biocthis),</span>
<span class="co">#&gt; https://github.com/lcolladotor/biocthisbiocthis - R package version</span>
<span class="co">#&gt; 1.3.7, &lt;URL: http://www.bioconductor.org/packages/biocthis&gt;.</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; Collado-Torres L (2021). "Automate package and project setup for</span>
<span class="co">#&gt; Bioconductor packages." _bioRxiv_. doi: 10.1101/TODO (URL:</span>
<span class="co">#&gt; https://doi.org/10.1101/TODO), &lt;URL:</span>
<span class="co">#&gt; https://www.biorxiv.org/content/10.1101/TODO&gt;.</span>
<span class="co">#&gt; </span>
<span class="co">#&gt; To see these entries in BibTeX format, use 'print(&lt;citation&gt;,</span>
<span class="co">#&gt; bibtex=TRUE)', 'toBibtex(.)', or set</span>
<span class="co">#&gt; 'options(citation.bibtex.max=999)'.</span></code></pre></div>
</div>
</div>
<div id="quick-start-to-using-to-biocthis" class="section level1">
<h1 class="hasAnchor">
<a href="#quick-start-to-using-to-biocthis" class="anchor" aria-hidden="true"></a>Quick start to using to <code>biocthis</code>
</h1>
<p><em><a href="https://bioconductor.org/packages/3.14/biocthis" class="external-link">biocthis</a></em> is an R package that expands <em><a href="https://CRAN.R-project.org/package=usethis" class="external-link">usethis</a></em> with Bioconductor-friendly templates. These templates will help you quickly create an R package that either has Bioconductor dependencies or that you are thinking of submitting to Bioconductor one day. <em><a href="https://bioconductor.org/packages/3.14/biocthis" class="external-link">biocthis</a></em> has functions that can also enhance your current R packages that either are already distributed by Bioconductor or have Bioconductor dependencies. <em><a href="https://bioconductor.org/packages/3.14/biocthis" class="external-link">biocthis</a></em> also includes a Bioconductor-friendly <a href="https://github.com/features/actions" class="external-link">GitHub Actions</a> workflow for your R package(s). To use the functions in this package, you need to load it as shown below.</p>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="st"><a href="https://github.com/lcolladotor/biocthis" class="external-link">"biocthis"</a></span><span class="op">)</span>

<span class="co">## Load other R packages used in this vignette</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="st"><a href="https://usethis.r-lib.org" class="external-link">"usethis"</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="st"><a href="https://github.com/r-lib/styler" class="external-link">"styler"</a></span><span class="op">)</span></code></pre></div>
<div id="using-biocthis-in-your-r-package" class="section level2">
<h2 class="hasAnchor">
<a href="#using-biocthis-in-your-r-package" class="anchor" aria-hidden="true"></a>Using <code>biocthis</code> in your R package</h2>
<p>If you haven’t made an R package yet, you can do so using <em><a href="https://CRAN.R-project.org/package=usethis" class="external-link">usethis</a></em>. That is, utilize <code><a href="https://usethis.r-lib.org/reference/create_package.html" class="external-link">usethis::create_package()</a></code> with the package name of your choice. If you are using <a href="https://www.rstudio.com/products/rstudio/download" class="external-link">RStudio Desktop</a> this function will open a new RStudio window and open R in the correct location. Otherwise, you might need to use <code><a href="https://rdrr.io/r/base/getwd.html" class="external-link">setwd()</a></code> to change directories.</p>
<p>In this vignette we will create an example package called <code>biocthispkg</code> on a temporary directory and work in this directory in order to illustrate how the functions work. In a real world scenario, you would be working inside your R package and would not run <code><a href="../reference/biocthis_example_pkg.html">biocthis_example_pkg()</a></code>.</p>
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">## Create an example package for illustrative purposes.</span>
<span class="co">## Note: you do not need to run this for your own package!</span>
<span class="va">pkgdir</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/biocthis_example_pkg.html">biocthis_example_pkg</a></span><span class="op">(</span><span class="st">"biocthispkg"</span>, use_git <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>
<span class="co">#&gt; ✔ Creating '/tmp/Rtmpe6UipQ/biocthispkg/'</span>
<span class="co">#&gt; ✔ Setting active project to '/tmp/Rtmpe6UipQ/biocthispkg'</span>
<span class="co">#&gt; ✔ Creating 'R/'</span>
<span class="co">#&gt; ✔ Writing 'DESCRIPTION'</span>
<span class="co">#&gt; Package: biocthispkg</span>
<span class="co">#&gt; Title: What the Package Does (One Line, Title Case)</span>
<span class="co">#&gt; Version: 0.0.0.9000</span>
<span class="co">#&gt; Authors@R (parsed):</span>
<span class="co">#&gt;     * First Last &lt;first.last@example.com&gt; [aut, cre] (YOUR-ORCID-ID)</span>
<span class="co">#&gt; Description: What the package does (one paragraph).</span>
<span class="co">#&gt; License: `use_mit_license()`, `use_gpl3_license()` or friends to pick a</span>
<span class="co">#&gt;     license</span>
<span class="co">#&gt; Encoding: UTF-8</span>
<span class="co">#&gt; LazyData: true</span>
<span class="co">#&gt; Roxygen: list(markdown = TRUE)</span>
<span class="co">#&gt; RoxygenNote: 7.1.1</span>
<span class="co">#&gt; ✔ Writing 'NAMESPACE'</span>
<span class="co">#&gt; ✔ Setting active project to '&lt;no active project&gt;'</span>
<span class="co">#&gt; ✔ Setting active project to '/tmp/Rtmpe6UipQ/biocthispkg'</span>
<span class="co">#&gt; ✔ Initialising Git repo</span>
<span class="co">#&gt; ✔ Adding '.Rproj.user', '.Rhistory', '.Rdata', '.httr-oauth', '.DS_Store' to '.gitignore'</span></code></pre></div>
<p>Once you have created a package, you can use <code><a href="../reference/use_bioc_pkg_templates.html">use_bioc_pkg_templates()</a></code> to create a set of scripts in the <code>dev</code> (developer) directory.</p>
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">## Create the bioc templates</span>
<span class="fu">biocthis</span><span class="fu">::</span><span class="fu"><a href="../reference/use_bioc_pkg_templates.html">use_bioc_pkg_templates</a></span><span class="op">(</span><span class="op">)</span>
<span class="co">#&gt; ✔ Creating 'dev/'</span>
<span class="co">#&gt; ✔ Adding '^dev$' to '.Rbuildignore'</span>
<span class="co">#&gt; ✔ Writing 'dev/01_create_pkg.R'</span>
<span class="co">#&gt; ✔ Writing 'dev/02_git_github_setup.R'</span>
<span class="co">#&gt; ✔ Writing 'dev/03_core_files.R'</span>
<span class="co">#&gt; ✔ Writing 'dev/04_update.R'</span></code></pre></div>
<p>If you run <code><a href="../reference/use_bioc_pkg_templates.html">use_bioc_pkg_templates()</a></code> inside RStudio Desktop, then all the scripts will open on your RStudio window. Each script contains comments that will guide you on the steps you need to do to create your Bioconductor-friendly R package. These scripts are:</p>
<ul>
<li>
<code>01_create_pkg.R</code>
<ul>
<li>Helps you install R packages needed for developing R packages with these template scripts.</li>
<li>Helps you check if the R package name you chose is available.</li>
<li>Includes the steps up to running <code><a href="../reference/use_bioc_pkg_templates.html">use_bioc_pkg_templates()</a></code>.</li>
</ul>
</li>
<li>
<code>02_git_github_setup.R</code>
<ul>
<li>Ignores the <code>*.Rproj</code> files to comply with Bioconductor’s requirements</li>
<li>Initializes a git repository</li>
<li>Creates the corresponding GitHub repository</li>
</ul>
</li>
<li>
<code>03_core_files.R</code>
<ul>
<li>Creates Bioconductor-friendly <code>README.Rmd</code> and <code>NEWS.md</code> files</li>
<li>Creates Bioconductor-friendly GitHub template for issues</li>
<li>Uses the tidyverse-style GitHub contributing and code of conduct files</li>
<li>Creates a template Bioconductor-friendly <code>CITATION</code> file</li>
<li>Adds several badges to the <code>README.Rmd</code> file <a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a>
</li>
<li>Sets up unit tests using <em><a href="https://CRAN.R-project.org/package=testthat" class="external-link">testthat</a></em> (Wickham, 2011)</li>
<li>Adds a Bioconductor-friendly GitHub Actions workflow</li>
<li>Deploys an initial documentation website using <em><a href="https://CRAN.R-project.org/package=pkgdown" class="external-link">pkgdown</a></em> (Wickham, Hesselberth, and Salmon, 2021)</li>
</ul>
</li>
<li>
<code>04_update.R</code>
<ul>
<li>Automatically styles the R code in your package using <em><a href="https://CRAN.R-project.org/package=styler" class="external-link">styler</a></em> (Müller and Walthert, 2021)</li>
<li>Update the documentation file using <em><a href="https://CRAN.R-project.org/package=devtools" class="external-link">devtools</a></em> (Wickham, Hester, and Chang, 2021)</li>
</ul>
</li>
</ul>
<p>Many of these steps are powered by <em><a href="https://CRAN.R-project.org/package=usethis" class="external-link">usethis</a></em> (Wickham and Bryan, 2021) with some of them utilizing <em><a href="https://bioconductor.org/packages/3.14/biocthis" class="external-link">biocthis</a></em> (Collado-Torres, 2021).</p>
</div>
</div>
<div id="biocthis-functions-overview" class="section level1">
<h1 class="hasAnchor">
<a href="#biocthis-functions-overview" class="anchor" aria-hidden="true"></a><code>biocthis</code> functions overview</h1>
<p>The <code>dev</code> scripts use the different functions provided by <em><a href="https://bioconductor.org/packages/3.14/biocthis" class="external-link">biocthis</a></em> in the suggested order. However, below we give a brief overview of what they do.</p>
<div id="bioc_style" class="section level2">
<h2 class="hasAnchor">
<a href="#bioc_style" class="anchor" aria-hidden="true"></a><code>bioc_style()</code>
</h2>
<p><code><a href="../reference/bioc_style.html">bioc_style()</a></code> helps you automatically apply a coding style to your R package files using <em><a href="https://CRAN.R-project.org/package=styler" class="external-link">styler</a></em> (Müller and Walthert, 2021) that is based on the <a href="https://style.tidyverse.org/" class="external-link">tidyverse coding style guide</a> but modified to make it more similar to the <a href="http://bioconductor.org/developers/how-to/coding-style/" class="external-link">Bioconductor coding style guide</a>.</p>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">## Automatically style the example package</span>
<span class="fu">styler</span><span class="fu">::</span><span class="fu"><a href="https://styler.r-lib.org/reference/style_pkg.html" class="external-link">style_pkg</a></span><span class="op">(</span><span class="va">pkgdir</span>, transformers <span class="op">=</span> <span class="fu">biocthis</span><span class="fu">::</span><span class="fu"><a href="../reference/bioc_style.html">bioc_style</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span>
<span class="co">#&gt; ────────────────────────────────────────</span>
<span class="co">#&gt; Status   Count   Legend </span>
<span class="co">#&gt; ✔    0   File unchanged.</span>
<span class="co">#&gt; ℹ    0   File changed.</span>
<span class="co">#&gt; ✖    0   Styling threw an error.</span>
<span class="co">#&gt; ────────────────────────────────────────</span></code></pre></div>
</div>
<div id="use_bioc_citation" class="section level2">
<h2 class="hasAnchor">
<a href="#use_bioc_citation" class="anchor" aria-hidden="true"></a><code>use_bioc_citation()</code>
</h2>
<p><code><a href="../reference/use_bioc_citation.html">use_bioc_citation()</a></code> creates an R package <code>CITATION</code> file at <code>inst/CITATION</code> that is pre-populated with information you might want to use for your (future) Bioconductor package such as the Bioconductor DOIs and reference a journal article describing your package (that you might consider submitting to <a href="https://www.biorxiv.org/" class="external-link">bioRxiv</a> as a pre-print first). Alternatively, use <code><a href="https://usethis.r-lib.org/reference/use_citation.html" class="external-link">usethis::use_citation()</a></code>.</p>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">## Create a template CITATION file that is Bioconductor-friendly</span>
<span class="fu">biocthis</span><span class="fu">::</span><span class="fu"><a href="../reference/use_bioc_citation.html">use_bioc_citation</a></span><span class="op">(</span><span class="op">)</span>
<span class="co">#&gt; ✔ Creating 'inst/'</span>
<span class="co">#&gt; ✔ Writing 'inst/CITATION'</span>
<span class="co">#&gt; • Edit 'inst/CITATION'</span></code></pre></div>
</div>
<div id="use_bioc_description" class="section level2">
<h2 class="hasAnchor">
<a href="#use_bioc_description" class="anchor" aria-hidden="true"></a><code>use_bioc_description()</code>
</h2>
<p><code><a href="../reference/use_bioc_description.html">use_bioc_description()</a></code> creates an R package <code>DESCRIPTION</code> file that is pre-populated with information you might want to use for your (future) Bioconductor package such as links to the Bioconductor Support Website and <code>biocViews</code>. You will still need to manually edit the file. Alternatively, use <code><a href="https://usethis.r-lib.org/reference/use_description.html" class="external-link">usethis::use_description()</a></code>.</p>
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">## Create a template DESCRIPTION file that is Bioconductor-friendly</span>
<span class="fu">biocthis</span><span class="fu">::</span><span class="fu"><a href="../reference/use_bioc_description.html">use_bioc_description</a></span><span class="op">(</span><span class="op">)</span>
<span class="co">#&gt; ✔ Leaving 'DESCRIPTION' unchanged</span>
<span class="co">#&gt; Package: biocthispkg</span>
<span class="co">#&gt; Title: What the Package Does (One Line, Title Case)</span>
<span class="co">#&gt; Version: 0.99.0</span>
<span class="co">#&gt; Date: 2021-08-09</span>
<span class="co">#&gt; Authors@R (parsed):</span>
<span class="co">#&gt;     * First Last &lt;first.last@example.com&gt; [aut, cre] (YOUR-ORCID-ID)</span>
<span class="co">#&gt; Description: What the package does (one paragraph).</span>
<span class="co">#&gt; License: Artistic-2.0</span>
<span class="co">#&gt; URL:</span>
<span class="co">#&gt; BugReports: https://support.bioconductor.org/t/biocthispkg</span>
<span class="co">#&gt; biocViews: Software</span>
<span class="co">#&gt; Encoding: UTF-8</span>
<span class="co">#&gt; LazyData: true</span>
<span class="co">#&gt; Roxygen: list(markdown = TRUE)</span>
<span class="co">#&gt; RoxygenNote: 7.1.1</span></code></pre></div>
</div>
<div id="use_bioc_github_action" class="section level2">
<h2 class="hasAnchor">
<a href="#use_bioc_github_action" class="anchor" aria-hidden="true"></a><code>use_bioc_github_action()</code>
</h2>
<div id="getting-started" class="section level3">
<h3 class="hasAnchor">
<a href="#getting-started" class="anchor" aria-hidden="true"></a>Getting started</h3>
<p><code><a href="../reference/use_bioc_github_action.html">use_bioc_github_action()</a></code> creates a GitHub Actions (GHA) workflow file that is configured to be Bioconductor-friendly. Alternatively, use <code><a href="https://usethis.r-lib.org/reference/use_github_action.html" class="external-link">usethis::use_github_action()</a></code> for the general GitHub Actions workflow maintained by <code>r-lib/actions</code>. If this is your first time seeing the words <em>GitHub Actions</em>, we highly recommend that you watch <a href="https://www.jimhester.com/talk/2020-rsc-github-actions/" class="external-link">Jim Hester’s <code>rstudio::conf(2020)</code> talk on this subject</a>. Here is how you can add this GHA workflow to your R package:</p>
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">## Create a GitHub Actions workflow that is Bioconductor-friendly</span>
<span class="fu">biocthis</span><span class="fu">::</span><span class="fu"><a href="../reference/use_bioc_github_action.html">use_bioc_github_action</a></span><span class="op">(</span><span class="op">)</span>
<span class="co">#&gt; ✔ Creating '.github/'</span>
<span class="co">#&gt; ✔ Adding '^\\.github$' to '.Rbuildignore'</span>
<span class="co">#&gt; ✔ Adding '*.html' to '.github/.gitignore'</span>
<span class="co">#&gt; ✔ Creating '.github/workflows/'</span>
<span class="co">#&gt; ✔ Writing '.github/workflows/check-bioc.yml'</span></code></pre></div>
</div>
<div id="main-gha-workflow-features" class="section level3">
<h3 class="hasAnchor">
<a href="#main-gha-workflow-features" class="anchor" aria-hidden="true"></a>Main GHA workflow features</h3>
<p>This <a href="https://github.com/features/actions" class="external-link">GitHub Actions</a> (GHA) workflow is based on <a href="https://github.com/r-lib/actions/blob/master/examples/check-standard.yaml" class="external-link">r-lib/actions//examples/check-standard.yaml</a> and others. The goal is to provide on demand <code>R CMD check</code>s on Linux, macOS and Windows using a similar setup to Bioconductor-devel and release branches. Some key features that make this GHA workflow Bioconductor-friendly are:</p>
<ul>
<li>It runs <code>R CMD check</code> on the same platforms (Linux, macOS and Windows) that Bioconductor supports.</li>
<li>It runs <code><a href="https://rdrr.io/pkg/BiocCheck/man/BiocCheck.html" class="external-link">BiocCheck::BiocCheck()</a></code> on all these platforms, unlike the Bioconductor nightly builds. <em><a href="https://bioconductor.org/packages/3.14/BiocCheck" class="external-link">BiocCheck</a></em> is complementary to <code>R CMD check</code> and can help you improve your R package.</li>
<li>It uses the <a href="https://www.bioconductor.org/help/docker/" class="external-link">Bioconductor devel and release dockers</a> to test your package on Linux. Since all system dependencies required by Bioconductor packages are already included in these docker images, it’s unlikely that you’ll need to fiddle with Linux system dependencies. The information on the docker image is then used for configuring the macOS and Windows tests.</li>
</ul>
</div>
<div id="additional-features" class="section level3">
<h3 class="hasAnchor">
<a href="#additional-features" class="anchor" aria-hidden="true"></a>Additional features</h3>
<p>Furthermore, the <code><a href="../reference/use_bioc_github_action.html">use_bioc_github_action()</a></code> GHA workflow provides the following features:</p>
<ul>
<li>It runs <em><a href="https://CRAN.R-project.org/package=covr" class="external-link">covr</a></em> (Hester, 2020) unless disabled by the environment variable <strong><code>run_covr</code></strong> (see the first few lines of the workflow).</li>
<li>It automatically deploys a documentation website using <em><a href="https://CRAN.R-project.org/package=pkgdown" class="external-link">pkgdown</a></em> (Wickham, Hesselberth, and Salmon, 2021) unless disabled by the environment variable <strong><code>run_pkgdown</code></strong> (see the first few lines of the workflow).</li>
<li>It displays the information from <em><a href="https://CRAN.R-project.org/package=testthat" class="external-link">testthat</a></em> (Wickham, 2011) unless disabled by the environment variable <strong><code>has_testthat</code></strong> (see the first few lines of the workflow). Similarly, <strong><code>has_RUnit</code></strong> controls whether you want to run the <code>RUnit</code> tests described in the <a href="http://bioconductor.org/developers/how-to/unitTesting-guidelines/" class="external-link">Bioconductor unit testing guidelines</a>.</li>
<li>It caches the R packages and re-uses them for future tests except if you use the keyword <code>/nocache</code> in your commit message. Using <strong><code>/nocache</code></strong> can be helpful for debugging purposes. The caches are specific to the platform, the R version, and the Bioconductor version <a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a>. These caches help you speed up your checks and are updated after a successful build.</li>
<li>The machines provided by GitHub have 7GB of RAM, 2 cores and 14 GB of disk as noted in their <a href="https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners" class="external-link">help pages</a>. It’s free for open source projects, but you can also pay to use it on private repositories as explained <a href="https://github.com/features/actions" class="external-link">in their features website</a>.</li>
</ul>
</div>
<div id="configure-options" class="section level3">
<h3 class="hasAnchor">
<a href="#configure-options" class="anchor" aria-hidden="true"></a>Configure options</h3>
<p>To help you set some of these configuration environment variables in the GHA workflow, <code><a href="../reference/use_bioc_github_action.html">use_bioc_github_action()</a></code> has a few arguments that are used to update a template and customize it for your particular repository. Several of the arguments in <code><a href="../reference/use_bioc_github_action.html">use_bioc_github_action()</a></code> use <code><a href="https://rdrr.io/r/base/options.html" class="external-link">base::getOption()</a></code>, which enables you to edit your R profile file with <code><a href="https://usethis.r-lib.org/reference/edit.html" class="external-link">usethis::edit_r_profile()</a></code> and add lines such as the ones mentioned in the code below.</p>
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">## Open your .Rprofile file with usethis::edit_r_profile()</span>

<span class="co">## For biocthis</span>
<span class="fu"><a href="https://rdrr.io/r/base/options.html" class="external-link">options</a></span><span class="op">(</span><span class="st">"biocthis.pkgdown"</span> <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/options.html" class="external-link">options</a></span><span class="op">(</span><span class="st">"biocthis.testthat"</span> <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
</div>
<div id="automatically-scheduled-tests" class="section level3">
<h3 class="hasAnchor">
<a href="#automatically-scheduled-tests" class="anchor" aria-hidden="true"></a>Automatically scheduled tests</h3>
<p>You could also edit the resulting GHA workflow to run automatically every few days (for example, every Monday) by adding a <code>cron</code> line as described in the <a href="https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onschedule" class="external-link">official GHA documentation</a>. This could of interest to you in some situations, though you should also be aware that it will use your GHA compute time that can have limits depending on your GitHub account and repository settings. If you are setting up a <code>cron</code> scheduled job, you might find <a href="https://crontab.guru/" class="external-link">crontab.guru</a> useful.</p>
<p>Ultimately, there are many things you can do with GHA and you might want to use workflow as the basis for building <em><a href="https://CRAN.R-project.org/package=bookdown" class="external-link">bookdown</a></em> or <em><a href="https://CRAN.R-project.org/package=rmarkdown" class="external-link">rmarkdown</a></em> websites, or even <code>docker</code> images. Some examples are:</p>
<ul>
<li>
<a href="https://github.com/lcolladotor/bioc_team_ds/blob/master/.github/workflows/build_book_bioc_docker.yml" class="external-link">lcolladotor/bioc_team_ds</a> for <em><a href="https://CRAN.R-project.org/package=bookdown" class="external-link">bookdown</a></em>.</li>
<li>
<a href="https://github.com/LieberInstitute/recountWorkshop2020/blob/master/.github/workflows/check-bioc.yml" class="external-link">LieberInstitute/recountWorkshop2020</a> for creating a <code>docker</code> image at the end.</li>
</ul>
</div>
<div id="notes-about-gha-workflows" class="section level3">
<h3 class="hasAnchor">
<a href="#notes-about-gha-workflows" class="anchor" aria-hidden="true"></a>Notes about GHA workflows</h3>
<p>Using a GitHub Actions workflow with Bioconductor-devel (R-devel six months in the year), regardless of which GHA workflow you use specifically, will expose you to issues with installing R packages in the latest versions of Bioconductor, CRAN, GitHub and elsewhere. At <a href="https://github.com/r-lib/actions#where-to-find-help" class="external-link">r-lib/actions#where-to-find-help</a> you can find a list of steps you can take to get help for R GHA workflows. In the end, you might have to ask for help in:</p>
<ul>
<li>developer-oriented mailing lists,</li>
<li>GitHub repositories for the packages you have issues installing them with,</li>
<li>GitHub Actions repositories, and elsewhere.</li>
</ul>
<p>That is, the GHA workflow provided by <em><a href="https://bioconductor.org/packages/3.14/biocthis" class="external-link">biocthis</a></em> can break depending on changes upstream of it. In particular, it can stop working:</p>
<ul>
<li>just prior to a new R release (unless <code>r-lib/actions</code> supports R <code>alpha</code> releases),</li>
<li>if the required Bioconductor docker image is not available (for example, due to issues building these images based on dependencies on <code>rocker</code> and other upstream tools) <a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a>.</li>
</ul>
<p>We highly recommend watching any developments as they happen at <em><a href="https://github.com/r-lib/actions" class="external-link">actions</a></em> since the <code>r-lib</code> team does an excellent job keeping their GHA workflows updated. You can do so by subscribing to the <a href="https://github.com/r-lib/actions/commits/master.atom" class="external-link">RSS atom feed</a> for commits in their repository processed through <a href="http://feeds.feedburner.com/RecentCommitsToActionsmaster" class="external-link">RSS FeedBurner</a> that you can <a href="https://feedburner.google.com/fb/a/mailverify?uri=RecentCommitsToActionsmaster" class="external-link">subscribe to by email</a>.</p>
<p>If you are interested in learning more details about how this GHA workflow came to be, check the <a href="https://lcolladotor.github.io/biocthis/articles/biocthis_dev_notes.html" class="external-link"><code>biocthis developer notes</code> vignette</a>.</p>
</div>
</div>
<div id="use_bioc_issue_template" class="section level2">
<h2 class="hasAnchor">
<a href="#use_bioc_issue_template" class="anchor" aria-hidden="true"></a><code>use_bioc_issue_template()</code>
</h2>
<p><code><a href="../reference/use_bioc_issue_template.html">use_bioc_issue_template()</a></code> creates a GitHub issue template file that is pre-populated with information you might want to use for your (future) Bioconductor package such as links to the Bioconductor Support Website and examples of the information you can ask users to provide that will make it easier for you to help your users. Alternatively, use <code><a href="https://usethis.r-lib.org/reference/tidyverse.html" class="external-link">usethis::use_tidy_issue_template()</a></code>.</p>
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">## Create a template GitHub issue file that is Bioconductor-friendly</span>
<span class="fu">biocthis</span><span class="fu">::</span><span class="fu"><a href="../reference/use_bioc_issue_template.html">use_bioc_issue_template</a></span><span class="op">(</span><span class="op">)</span>
<span class="co">#&gt; ✔ Creating '.github/ISSUE_TEMPLATE/'</span>
<span class="co">#&gt; ✔ Writing '.github/ISSUE_TEMPLATE/issue_template.md'</span></code></pre></div>
</div>
<div id="use_bioc_news_md" class="section level2">
<h2 class="hasAnchor">
<a href="#use_bioc_news_md" class="anchor" aria-hidden="true"></a><code>use_bioc_news_md()</code>
</h2>
<p><code><a href="../reference/use_bioc_news_md.html">use_bioc_news_md()</a></code> creates a <code>NEWS.md</code> template file that is pre-populated with information you might want to use for your (future) Bioconductor package. Alternatively, use <code><a href="https://usethis.r-lib.org/reference/use_news_md.html" class="external-link">usethis::use_news_md()</a></code>.</p>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">## Create a template NEWS.md file that is Bioconductor-friendly</span>
<span class="fu">biocthis</span><span class="fu">::</span><span class="fu"><a href="../reference/use_bioc_news_md.html">use_bioc_news_md</a></span><span class="op">(</span><span class="op">)</span>
<span class="co">#&gt; ✔ Writing 'NEWS.md'</span></code></pre></div>
</div>
<div id="use_bioc_pkg_templates" class="section level2">
<h2 class="hasAnchor">
<a href="#use_bioc_pkg_templates" class="anchor" aria-hidden="true"></a><code>use_bioc_pkg_templates()</code>
</h2>
<p>This function was already described in detail in the previous main section.</p>
</div>
<div id="use_bioc_readme_rmd" class="section level2">
<h2 class="hasAnchor">
<a href="#use_bioc_readme_rmd" class="anchor" aria-hidden="true"></a><code>use_bioc_readme_rmd()</code>
</h2>
<p><code><a href="../reference/use_bioc_readme_rmd.html">use_bioc_readme_rmd()</a></code> creates a <code>README.Rmd</code> template file that is pre-populated with information you might want to use for your (future) Bioconductor package such as Bioconductor’s installation instructions, how to cite your package and links to the development tools you used. Alternatively, use <code><a href="https://usethis.r-lib.org/reference/use_readme_rmd.html" class="external-link">usethis::use_readme_rmd()</a></code>.</p>
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">## Create a template README.Rmd file that is Bioconductor-friendly</span>
<span class="fu">biocthis</span><span class="fu">::</span><span class="fu"><a href="../reference/use_bioc_readme_rmd.html">use_bioc_readme_rmd</a></span><span class="op">(</span><span class="op">)</span>
<span class="co">#&gt; ✔ Writing 'README.Rmd'</span>
<span class="co">#&gt; ✔ Adding '^README\\.Rmd$' to '.Rbuildignore'</span>
<span class="co">#&gt; ✔ Writing '.git/hooks/pre-commit'</span></code></pre></div>
</div>
<div id="use_bioc_support" class="section level2">
<h2 class="hasAnchor">
<a href="#use_bioc_support" class="anchor" aria-hidden="true"></a><code>use_bioc_support()</code>
</h2>
<p><code><a href="../reference/use_bioc_support.html">use_bioc_support()</a></code> creates a template GitHub support template file that is pre-populated with information you might want to use for your (future) Bioconductor package such where to ask for help including the Bioconductor Support website. Alternatively, use <code><a href="https://usethis.r-lib.org/reference/tidyverse.html" class="external-link">usethis::use_tidy_support()</a></code>.</p>
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">## Create a template GitHub support file that is Bioconductor-friendly</span>
<span class="fu">biocthis</span><span class="fu">::</span><span class="fu"><a href="../reference/use_bioc_support.html">use_bioc_support</a></span><span class="op">(</span><span class="op">)</span>
<span class="co">#&gt; ✔ Writing '.github/SUPPORT.md'</span></code></pre></div>
</div>
<div id="use_bioc_vignette" class="section level2">
<h2 class="hasAnchor">
<a href="#use_bioc_vignette" class="anchor" aria-hidden="true"></a><code>use_bioc_vignette()</code>
</h2>
<p><code><a href="../reference/use_bioc_vignette.html">use_bioc_vignette()</a></code> creates a template vignette file that is pre-populated with information you might want to use for your (future) Bioconductor package. This template includes information on how to cite other packages using <em><a href="https://CRAN.R-project.org/package=RefManageR" class="external-link">RefManageR</a></em>, styling your vignette with <em><a href="https://bioconductor.org/packages/3.14/BiocStyle" class="external-link">BiocStyle</a></em>, instructions on how to install your package from Bioconductor, where to ask for help, information a user might need to know before they use your package, as well as the reproducibility information on how the vignette was made powered by <em><a href="https://CRAN.R-project.org/package=sessioninfo" class="external-link">sessioninfo</a></em>. You will need to spend a significant amount of time editing this vignette as you develop your R package. Alternatively, use <code><a href="https://usethis.r-lib.org/reference/use_vignette.html" class="external-link">usethis::use_vignette()</a></code>.</p>
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">## Create a template vignette file that is Bioconductor-friendly</span>
<span class="fu">biocthis</span><span class="fu">::</span><span class="fu"><a href="../reference/use_bioc_vignette.html">use_bioc_vignette</a></span><span class="op">(</span><span class="st">"biocthispkg"</span>, <span class="st">"Introduction to biocthispkg"</span><span class="op">)</span>
<span class="co">#&gt; ✔ Adding 'knitr' to Suggests field in DESCRIPTION</span>
<span class="co">#&gt; • Use `requireNamespace("knitr", quietly = TRUE)` to test if package is installed</span>
<span class="co">#&gt; • Then directly refer to functons like `knitr::fun()` (replacing `fun()`).</span>
<span class="co">#&gt; ✔ Adding 'BiocStyle' to Suggests field in DESCRIPTION</span>
<span class="co">#&gt; • Use `requireNamespace("BiocStyle", quietly = TRUE)` to test if package is installed</span>
<span class="co">#&gt; • Then directly refer to functons like `BiocStyle::fun()` (replacing `fun()`).</span>
<span class="co">#&gt; ✔ Adding 'RefManageR' to Suggests field in DESCRIPTION</span>
<span class="co">#&gt; • Use `requireNamespace("RefManageR", quietly = TRUE)` to test if package is installed</span>
<span class="co">#&gt; • Then directly refer to functons like `RefManageR::fun()` (replacing `fun()`).</span>
<span class="co">#&gt; ✔ Adding 'sessioninfo' to Suggests field in DESCRIPTION</span>
<span class="co">#&gt; • Use `requireNamespace("sessioninfo", quietly = TRUE)` to test if package is installed</span>
<span class="co">#&gt; • Then directly refer to functons like `sessioninfo::fun()` (replacing `fun()`).</span>
<span class="co">#&gt; ✔ Setting VignetteBuilder field in DESCRIPTION to 'knitr'</span>
<span class="co">#&gt; ✔ Adding 'inst/doc' to '.gitignore'</span>
<span class="co">#&gt; ✔ Creating 'vignettes/'</span>
<span class="co">#&gt; ✔ Adding '*.html', '*.R' to 'vignettes/.gitignore'</span>
<span class="co">#&gt; ✔ Adding 'rmarkdown' to Suggests field in DESCRIPTION</span>
<span class="co">#&gt; • Use `requireNamespace("rmarkdown", quietly = TRUE)` to test if package is installed</span>
<span class="co">#&gt; • Then directly refer to functons like `rmarkdown::fun()` (replacing `fun()`).</span>
<span class="co">#&gt; ✔ Writing 'vignettes/biocthispkg.Rmd'</span>
<span class="co">#&gt; • Edit 'vignettes/biocthispkg.Rmd'</span></code></pre></div>
</div>
</div>
<div id="acknowledgments" class="section level1">
<h1 class="hasAnchor">
<a href="#acknowledgments" class="anchor" aria-hidden="true"></a>Acknowledgments</h1>
<p><em><a href="https://bioconductor.org/packages/3.14/biocthis" class="external-link">biocthis</a></em> wouldn’t have been possible without the help of many other R package developers. Please read the full story at the <a href="https://lcolladotor.github.io/biocthis/articles/biocthis_dev_notes.html" class="external-link"><code>biocthis developer notes</code> vignette</a>.</p>
<p>Thank you very much! 🙌🏽😊</p>
</div>
<div id="reproducibility" class="section level1">
<h1 class="hasAnchor">
<a href="#reproducibility" class="anchor" aria-hidden="true"></a>Reproducibility</h1>
<p>The <em><a href="https://bioconductor.org/packages/3.14/biocthis" class="external-link">biocthis</a></em> package (Collado-Torres, 2021) was made possible thanks to:</p>
<ul>
<li>R (R Core Team, 2021)</li>
<li>
<em><a href="https://bioconductor.org/packages/3.14/BiocStyle" class="external-link">BiocStyle</a></em> (Oleś, 2021)</li>
<li>
<em><a href="https://CRAN.R-project.org/package=covr" class="external-link">covr</a></em> (Hester, 2020)</li>
<li>
<em><a href="https://CRAN.R-project.org/package=devtools" class="external-link">devtools</a></em> (Wickham, Hester, and Chang, 2021)</li>
<li>
<em><a href="https://CRAN.R-project.org/package=fs" class="external-link">fs</a></em> (Hester and Wickham, 2020)</li>
<li>
<em><a href="https://CRAN.R-project.org/package=glue" class="external-link">glue</a></em> (Hester, 2020)</li>
<li>
<em><a href="https://CRAN.R-project.org/package=knitr" class="external-link">knitr</a></em> (Xie, 2021)</li>
<li>
<em><a href="https://CRAN.R-project.org/package=pkgdown" class="external-link">pkgdown</a></em> (Wickham, Hesselberth, and Salmon, 2021)</li>
<li>
<em><a href="https://CRAN.R-project.org/package=rlang" class="external-link">rlang</a></em> (Henry and Wickham, 2021)</li>
<li>
<em><a href="https://CRAN.R-project.org/package=RefManageR" class="external-link">RefManageR</a></em> (McLean, 2017)</li>
<li>
<em><a href="https://CRAN.R-project.org/package=rmarkdown" class="external-link">rmarkdown</a></em> (Allaire, Xie, McPherson, Luraschi, Ushey, Atkins, Wickham, Cheng, Chang, and Iannone, 2021)</li>
<li>
<em><a href="https://CRAN.R-project.org/package=sessioninfo" class="external-link">sessioninfo</a></em> (Csárdi, core, Wickham, Chang, Flight, Müller, and Hester, 2018)</li>
<li>
<em><a href="https://CRAN.R-project.org/package=styler" class="external-link">styler</a></em> (Müller and Walthert, 2021)</li>
<li>
<em><a href="https://CRAN.R-project.org/package=testthat" class="external-link">testthat</a></em> (Wickham, 2011)</li>
<li>
<em><a href="https://CRAN.R-project.org/package=usethis" class="external-link">usethis</a></em> (Wickham and Bryan, 2021)</li>
</ul>
<p>This package was developed using <em><a href="https://bioconductor.org/packages/3.14/biocthis" class="external-link">biocthis</a></em>.</p>
<p>Code for creating the vignette</p>
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">## Create the vignette</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="st"><a href="https://github.com/rstudio/rmarkdown" class="external-link">"rmarkdown"</a></span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/system.time.html" class="external-link">system.time</a></span><span class="op">(</span><span class="fu"><a href="https://pkgs.rstudio.com/rmarkdown/reference/render.html" class="external-link">render</a></span><span class="op">(</span><span class="st">"biocthis.Rmd"</span>, <span class="st">"BiocStyle::html_document"</span><span class="op">)</span><span class="op">)</span>

<span class="co">## Extract the R code</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="st"><a href="https://yihui.org/knitr/" class="external-link">"knitr"</a></span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/pkg/knitr/man/knit.html" class="external-link">knit</a></span><span class="op">(</span><span class="st">"biocthis.Rmd"</span>, tangle <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<p>Date the vignette was generated.</p>
<pre><code>#&gt; [1] "2021-08-09 23:54:28 UTC"</code></pre>
<p>Wallclock time spent generating the vignette.</p>
<pre><code>#&gt; Time difference of 3.473 secs</code></pre>
<p><code>R</code> session information.</p>
<pre><code>#&gt; ─ Session info ───────────────────────────────────────────────────────────────────────────────────────────────────────
#&gt;  setting  value                       
#&gt;  version  R version 4.1.0 (2021-05-18)
#&gt;  os       Ubuntu 20.04.2 LTS          
#&gt;  system   x86_64, linux-gnu           
#&gt;  ui       X11                         
#&gt;  language (EN)                        
#&gt;  collate  en_US.UTF-8                 
#&gt;  ctype    en_US.UTF-8                 
#&gt;  tz       UTC                         
#&gt;  date     2021-08-09                  
#&gt; 
#&gt; ─ Packages ───────────────────────────────────────────────────────────────────────────────────────────────────────────
#&gt;  package     * version    date       lib source                        
#&gt;  askpass       1.1        2019-01-13 [2] RSPM (R 4.1.0)                
#&gt;  backports     1.2.1      2020-12-09 [1] RSPM (R 4.1.0)                
#&gt;  BiocManager   1.30.16    2021-06-15 [2] CRAN (R 4.1.0)                
#&gt;  BiocStyle   * 2.21.3     2021-06-16 [1] Bioconductor                  
#&gt;  biocthis    * 1.3.7      2021-08-09 [1] Bioconductor                  
#&gt;  bookdown      0.22       2021-04-22 [1] RSPM (R 4.1.0)                
#&gt;  bslib         0.2.5.1    2021-05-18 [1] RSPM (R 4.1.0)                
#&gt;  cachem        1.0.5      2021-05-15 [2] RSPM (R 4.1.0)                
#&gt;  cli           3.0.1      2021-07-17 [2] RSPM (R 4.1.0)                
#&gt;  crayon        1.4.1      2021-02-08 [2] RSPM (R 4.1.0)                
#&gt;  credentials   1.3.1      2021-07-25 [2] RSPM (R 4.1.0)                
#&gt;  desc          1.3.0      2021-03-05 [2] RSPM (R 4.1.0)                
#&gt;  digest        0.6.27     2020-10-24 [2] RSPM (R 4.1.0)                
#&gt;  ellipsis      0.3.2      2021-04-29 [2] RSPM (R 4.1.0)                
#&gt;  evaluate      0.14       2019-05-28 [2] RSPM (R 4.1.0)                
#&gt;  fansi         0.5.0      2021-05-25 [2] RSPM (R 4.1.0)                
#&gt;  fastmap       1.1.0      2021-01-25 [2] RSPM (R 4.1.0)                
#&gt;  fs            1.5.0      2020-07-31 [2] RSPM (R 4.1.0)                
#&gt;  generics      0.1.0      2020-10-31 [2] RSPM (R 4.1.0)                
#&gt;  gert          1.3.1      2021-06-23 [2] RSPM (R 4.1.0)                
#&gt;  glue          1.4.2      2020-08-27 [2] RSPM (R 4.1.0)                
#&gt;  htmltools     0.5.1.1    2021-01-22 [1] RSPM (R 4.1.0)                
#&gt;  httr          1.4.2      2020-07-20 [2] RSPM (R 4.1.0)                
#&gt;  jquerylib     0.1.4      2021-04-26 [1] RSPM (R 4.1.0)                
#&gt;  jsonlite      1.7.2      2020-12-09 [2] RSPM (R 4.1.0)                
#&gt;  knitr         1.33       2021-04-24 [2] RSPM (R 4.1.0)                
#&gt;  lifecycle     1.0.0      2021-02-15 [2] RSPM (R 4.1.0)                
#&gt;  lubridate     1.7.10     2021-02-26 [1] RSPM (R 4.1.0)                
#&gt;  magrittr      2.0.1      2020-11-17 [2] RSPM (R 4.1.0)                
#&gt;  memoise       2.0.0      2021-01-26 [2] RSPM (R 4.1.0)                
#&gt;  openssl       1.4.4      2021-04-30 [2] RSPM (R 4.1.0)                
#&gt;  pillar        1.6.2      2021-07-29 [2] RSPM (R 4.1.0)                
#&gt;  pkgconfig     2.0.3      2019-09-22 [2] RSPM (R 4.1.0)                
#&gt;  pkgdown       1.6.1.9001 2021-08-05 [1] Github (r-lib/pkgdown@ce9781a)
#&gt;  plyr          1.8.6      2020-03-03 [1] RSPM (R 4.1.0)                
#&gt;  purrr         0.3.4      2020-04-17 [2] RSPM (R 4.1.0)                
#&gt;  R6            2.5.0      2020-10-28 [2] RSPM (R 4.1.0)                
#&gt;  ragg          1.1.3      2021-06-09 [1] RSPM (R 4.1.0)                
#&gt;  Rcpp          1.0.7      2021-07-07 [2] RSPM (R 4.1.0)                
#&gt;  RefManageR  * 1.3.0      2020-11-13 [1] RSPM (R 4.1.0)                
#&gt;  rlang         0.4.11     2021-04-30 [2] RSPM (R 4.1.0)                
#&gt;  rmarkdown     2.10       2021-08-06 [1] RSPM (R 4.1.0)                
#&gt;  roxygen2      7.1.1      2020-06-27 [2] RSPM (R 4.1.0)                
#&gt;  rprojroot     2.0.2      2020-11-15 [2] RSPM (R 4.1.0)                
#&gt;  rstudioapi    0.13       2020-11-12 [2] RSPM (R 4.1.0)                
#&gt;  sass          0.4.0      2021-05-12 [1] RSPM (R 4.1.0)                
#&gt;  sessioninfo * 1.1.1      2018-11-05 [2] RSPM (R 4.1.0)                
#&gt;  stringi       1.7.3      2021-07-16 [2] RSPM (R 4.1.0)                
#&gt;  stringr       1.4.0      2019-02-10 [2] RSPM (R 4.1.0)                
#&gt;  styler      * 1.5.1      2021-07-13 [1] RSPM (R 4.1.0)                
#&gt;  sys           3.4        2020-07-23 [2] RSPM (R 4.1.0)                
#&gt;  systemfonts   1.0.2      2021-05-11 [1] RSPM (R 4.1.0)                
#&gt;  textshaping   0.3.5      2021-06-09 [1] RSPM (R 4.1.0)                
#&gt;  tibble        3.1.3      2021-07-23 [2] RSPM (R 4.1.0)                
#&gt;  usethis     * 2.0.1      2021-02-10 [2] RSPM (R 4.1.0)                
#&gt;  utf8          1.2.2      2021-07-24 [2] RSPM (R 4.1.0)                
#&gt;  vctrs         0.3.8      2021-04-29 [2] RSPM (R 4.1.0)                
#&gt;  whisker       0.4        2019-08-28 [2] RSPM (R 4.1.0)                
#&gt;  withr         2.4.2      2021-04-18 [2] RSPM (R 4.1.0)                
#&gt;  xfun          0.25       2021-08-06 [2] RSPM (R 4.1.0)                
#&gt;  xml2          1.3.2      2020-04-23 [2] RSPM (R 4.1.0)                
#&gt;  yaml          2.2.1      2020-02-01 [2] RSPM (R 4.1.0)                
#&gt; 
#&gt; [1] /__w/_temp/Library
#&gt; [2] /usr/local/lib/R/site-library
#&gt; [3] /usr/local/lib/R/library</code></pre>
</div>
<div id="bibliography" class="section level1">
<h1 class="hasAnchor">
<a href="#bibliography" class="anchor" aria-hidden="true"></a>Bibliography</h1>
<p>This vignette was generated using <em><a href="https://bioconductor.org/packages/3.14/BiocStyle" class="external-link">BiocStyle</a></em> (Oleś, 2021) with <em><a href="https://CRAN.R-project.org/package=knitr" class="external-link">knitr</a></em> (Xie, 2021) and <em><a href="https://CRAN.R-project.org/package=rmarkdown" class="external-link">rmarkdown</a></em> (Allaire, Xie, McPherson, et al., 2021) running behind the scenes.</p>
<p>Citations made with <em><a href="https://CRAN.R-project.org/package=RefManageR" class="external-link">RefManageR</a></em> (McLean, 2017).</p>
<p>
<a id="bib-allaire2021rmarkdown"></a><a href="#cite-allaire2021rmarkdown">[1]</a><cite> J. Allaire, Y. Xie, J. McPherson, et al. <em>rmarkdown: Dynamic Documents for R</em>. R package version 2.10. 2021. URL: <a href="https://github.com/rstudio/rmarkdown" class="external-link">https://github.com/rstudio/rmarkdown</a>.</cite>
</p>
<p>
<a id="bib-colladotorres2021automate"></a><a href="#cite-colladotorres2021automate">[2]</a><cite> L. Collado-Torres. <em>Automate package and project setup for Bioconductor packages</em>. <a href="https://github.com/lcolladotor/biocthisbiocthis" class="external-link uri">https://github.com/lcolladotor/biocthisbiocthis</a> - R package version 1.3.7. 2021. DOI: <a href="https://doi.org/10.18129/B9.bioc.biocthis" class="external-link">10.18129/B9.bioc.biocthis</a>. URL: <a href="http://www.bioconductor.org/packages/biocthis" class="external-link">http://www.bioconductor.org/packages/biocthis</a>.</cite>
</p>
<p>
<a id="bib-csrdi2018sessioninfo"></a><a href="#cite-csrdi2018sessioninfo">[3]</a><cite> G. Csárdi, R. core, H. Wickham, et al. <em>sessioninfo: R Session Information</em>. R package version 1.1.1. 2018. URL: <a href="https://github.com/r-lib/sessioninfo#readme" class="external-link">https://github.com/r-lib/sessioninfo#readme</a>.</cite>
</p>
<p>
<a id="bib-henry2021rlang"></a><a href="#cite-henry2021rlang">[4]</a><cite> L. Henry and H. Wickham. <em>rlang: Functions for Base Types and Core R and ‘Tidyverse’ Features</em>. <a href="https://rlang.r-lib.org" class="external-link uri">https://rlang.r-lib.org</a>, <a href="https://github.com/r-lib/rlang" class="external-link uri">https://github.com/r-lib/rlang</a>. 2021.</cite>
</p>
<p>
<a id="bib-hester2020covr"></a><a href="#cite-hester2020covr">[5]</a><cite> J. Hester. <em>covr: Test Coverage for Packages</em>. <a href="https://covr.r-lib.org" class="external-link uri">https://covr.r-lib.org</a>, <a href="https://github.com/r-lib/covr" class="external-link uri">https://github.com/r-lib/covr</a>. 2020.</cite>
</p>
<p>
<a id="bib-hester2020glue"></a><a href="#cite-hester2020glue">[6]</a><cite> J. Hester. <em>glue: Interpreted String Literals</em>. <a href="https://github.com/tidyverse/glue" class="external-link uri">https://github.com/tidyverse/glue</a>, <a href="https://glue.tidyverse.org/" class="external-link uri">https://glue.tidyverse.org/</a>. 2020.</cite>
</p>
<p>
<a id="bib-hester2020cross"></a><a href="#cite-hester2020cross">[7]</a><cite> J. Hester and H. Wickham. <em>fs: Cross-Platform File System Operations Based on ‘libuv’</em>. <a href="http://fs.r-lib.org" class="external-link uri">http://fs.r-lib.org</a>, <a href="https://github.com/r-lib/fs" class="external-link uri">https://github.com/r-lib/fs</a>. 2020.</cite>
</p>
<p>
<a id="bib-mclean2017refmanager"></a><a href="#cite-mclean2017refmanager">[8]</a><cite> M. W. McLean. “RefManageR: Import and Manage BibTeX and BibLaTeX References in R”. In: <em>The Journal of Open Source Software</em> (2017). DOI: <a href="https://doi.org/10.21105/joss.00338" class="external-link">10.21105/joss.00338</a>.</cite>
</p>
<p>
<a id="bib-mller2021styler"></a><a href="#cite-mller2021styler">[9]</a><cite> K. Müller and L. Walthert. <em>styler: Non-Invasive Pretty Printing of R Code</em>. <a href="https://github.com/r-lib/styler" class="external-link uri">https://github.com/r-lib/styler</a>, <a href="https://styler.r-lib.org" class="external-link uri">https://styler.r-lib.org</a>. 2021.</cite>
</p>
<p>
<a id="bib-ole2021biocstyle"></a><a href="#cite-ole2021biocstyle">[10]</a><cite> A. Oleś. <em>BiocStyle: Standard styles for vignettes and other Bioconductor documents</em>. R package version 2.21.3. 2021. URL: <a href="https://github.com/Bioconductor/BiocStyle" class="external-link">https://github.com/Bioconductor/BiocStyle</a>.</cite>
</p>
<p>
<a id="bib-2021language"></a><a href="#cite-2021language">[11]</a><cite> R Core Team. <em>R: A Language and Environment for Statistical Computing</em>. R Foundation for Statistical Computing. Vienna, Austria, 2021. URL: <a href="https://www.R-project.org/" class="external-link">https://www.R-project.org/</a>.</cite>
</p>
<p>
<a id="bib-wickham2011testthat"></a><a href="#cite-wickham2011testthat">[12]</a><cite> H. Wickham. “testthat: Get Started with Testing”. In: <em>The R Journal</em> 3 (2011), pp. 5–10. URL: <a href="https://journal.r-project.org/archive/2011-1/RJournal_2011-1_Wickham.pdf" class="external-link">https://journal.r-project.org/archive/2011-1/RJournal_2011-1_Wickham.pdf</a>.</cite>
</p>
<p>
<a id="bib-wickham2021usethis"></a><a href="#cite-wickham2021usethis">[13]</a><cite> H. Wickham and J. Bryan. <em>usethis: Automate Package and Project Setup</em>. <a href="https://usethis.r-lib.org" class="external-link uri">https://usethis.r-lib.org</a>, <a href="https://github.com/r-lib/usethis" class="external-link uri">https://github.com/r-lib/usethis</a>. 2021.</cite>
</p>
<p>
<a id="bib-wickham2021pkgdown"></a><a href="#cite-wickham2021pkgdown">[14]</a><cite> H. Wickham, J. Hesselberth, and M. Salmon. <em>pkgdown: Make Static HTML Documentation for a Package</em>. <a href="https://pkgdown.r-lib.org" class="external-link uri">https://pkgdown.r-lib.org</a>, <a href="https://github.com/r-lib/pkgdown" class="external-link uri">https://github.com/r-lib/pkgdown</a>. 2021.</cite>
</p>
<p>
<a id="bib-wickham2021devtools"></a><a href="#cite-wickham2021devtools">[15]</a><cite> H. Wickham, J. Hester, and W. Chang. <em>devtools: Tools to Make Developing R Packages Easier</em>. <a href="https://devtools.r-lib.org/" class="external-link uri">https://devtools.r-lib.org/</a>, <a href="https://github.com/r-lib/devtools" class="external-link uri">https://github.com/r-lib/devtools</a>. 2021.</cite>
</p>
<p>
<a id="bib-xie2021knitr"></a><a href="#cite-xie2021knitr">[16]</a><cite> Y. Xie. <em>knitr: A General-Purpose Package for Dynamic Report Generation in R</em>. R package version 1.33. 2021. URL: <a href="https://yihui.org/knitr/" class="external-link">https://yihui.org/knitr/</a>.</cite>
</p>
</div>
<div class="footnotes">
<hr>
<ol>
<li id="fn1"><p>You might want to use <em><a href="https://CRAN.R-project.org/package=badger" class="external-link">badger</a></em> too, which has badges for Bioconductor download statistics. Some of the badges are only tailored for Bioconductor <em>software</em> packages, so you’ll have to edit them for annotation, experiment and workflow packages.<a href="#fnref1" class="footnote-back">↩︎</a></p></li>
<li id="fn2"><p>In some situations, you might want to change the <strong><code>cache_version</code></strong> environment variable to force GHA to use new caches.<a href="#fnref2" class="footnote-back">↩︎</a></p></li>
<li id="fn3"><p>See for example <a href="https://github.com/rocker-org/rocker-versioned2/issues/50" class="external-link">rocker-versioned2 issue 50</a>. <a href="#fnref3" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p></p>
<p>Developed by Leonardo Collado-Torres.</p>
</div>

<div class="pkgdown">
  <p></p>
<p>Site built with <a href="https://pkgdown.r-lib.org/" class="external-link external-link">pkgdown</a> 1.6.1.9001.</p>
</div>

      </footer>
</div>

  


  

  </body>
</html>
